dist: xenial

language: clojure
sudo: required
lein: lein
jdk:
  - openjdk8
services:
  - docker

branches:
  only:
    - master
    - wip
    - develop

install:
  - ./manage.sh help
  - nvm install $NODE_VERSION
  - node --version

before_script:
  - env | sort

script:
  - ./manage.sh $COMMAND

after_script:
  - docker images
  - docker ps

notifications:
  email: false

env:
  - NODE_VERSION=7.7.1 COMMAND=build
  - NODE_VERSION=7.7.1 COMMAND=test
  - NODE_VERSION=7.7.1 COMMAND=release-local
  - NODE_VERSION=7.7.1 COMMAND=release-docker
  - NODE_VERSION=7.7.1 COMMAND=run-release
  - NODE_VERSION=8.15.0 COMMAND=build
  - NODE_VERSION=8.15.0 COMMAND=test
  - NODE_VERSION=8.15.0 COMMAND=release-local
  - NODE_VERSION=8.15.0 COMMAND=release-docker
  - NODE_VERSION=8.15.0 COMMAND=run-release
