language: clojure
sudo: false
lein: lein

script:
  - ./scripts/build-tests
  - nvm install v5.10.1
  - node --version
  - node out/tests.js

jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
      - niwi@niwi.nz
    on_success: change
    on_failure: change
