dist: trusty
sudo: required

services: docker

language: bash

branches:
  only:
    - master
    - wip
    - develop

before_script:
  - env | sort

script:
  - ./manage.sh build
  - ./manage.sh release
  - docker build -t uxbox-backend backend-docker/
  - docker build -t uxbox-frontend frontend-docker/

after_script:
  - docker images
  - docker ps

notifications:
  email: false

env: # Environments
    - VERSION=beta
