dist: trusty
sudo: required

services: docker

language: bash

branches:
  only:
    - master
    - wip
    - develop

before_script:
  - env | sort

script:
  - ./manage.sh run
  - ./manage.sh release

after_script:
  - docker images
  - docker ps

notifications:
  email: false

env: # Environments
    - VERSION=beta
