dist: xenial
sudo: required

services: docker

language: java

jdk:
  - oraclejdk8

env:
  - NODE_VERSION=10.15.1

branches:
  only:
    - master
    - wip
    - develop

before_script:
  - env | sort
  - nvm install $NODE_VERSION
  - npm install
  - nvm use $NODE_VERSION
  - npm test

script:
  - ./manage.sh build
  - ./manage.sh release-local
  - ./manage.sh release-docker

after_script:
  - docker images
  - docker ps

notifications:
  email: false

env: # Environments
    - VERSION=beta
