dist: xenial

language: clojure
sudo: required
lein: lein
jdk:
  - openjdk8
services:
  - docker

branches:
  only:
    - master
    - wip
    - develop
    - build-refactor

install:
  - ./manage.sh help
  - nvm install $NODE_VERSION
  - node --version

before_script:
  - env | sort

script:
  - ./manage.sh $COMMAND

after_script:
  - docker images
  - docker ps

notifications:
  email: false

env:
  - NODE_VERSION=10.16.0 COMMAND=clean
  - NODE_VERSION=10.16.0 COMMAND=build-devenv
  #- NODE_VERSION=10.16.0 COMMAND=run-devenv
  # TODO Add unit test command(s)
  #- NODE_VERSION=10.16.0 COMMAND=test
  - NODE_VERSION=10.16.0 COMMAND=build-release
  - NODE_VERSION=10.16.0 COMMAND=build-release-frontend
  - NODE_VERSION=10.16.0 COMMAND=build-release-backend
  - NODE_VERSION=10.16.0 COMMAND=run-release
