dist: xenial

language: clojure
sudo: required
lein: lein
jdk:
  - openjdk8
  - openjdk10
  - openjdk11
services:
  - docker

branches:
  only:
    - master
    - wip
    - develop

install:
  - ./manage.sh build

before_script:
  - env | sort

script:
  - cd ./frontend
  - ./scripts/build-tests
  - nvm install $NODE_VERSION
  - node --version
  - node ./out/tests.js
  - cd ..
  - ./manage.sh release-local
  - ./manage.sh release-docker

after_script:
  - docker images
  - docker ps

notifications:
  email: false

env:
  - NODE_VERSION=7.7.1
  - NODE_VERSION=10.15.1
