dist: xenial

language: clojure
sudo: required
lein: lein
jdk:
  - openjdk8
  - openjdk10
  - openjdk11
services:
  - docker

branches:
  only:
    - master
    - wip
    - develop

before_script:
  - env | sort

script:
  - ./manage.sh build
  - ./manage.sh release-local
  - ./manage.sh release-docker

after_script:
  - docker images
  - docker ps

notifications:
  email: false

env: # Environments
    - VERSION=beta
