version: '2'

volumes:
  uxbox_front:
  uxbox_back:
  uxbox_db:

services:
    db:
        image: postgres:latest
        restart: always
        ports:
            - "5432:5432"
        environment:
            - "POSTGRES_DB=uxbox"
            - "POSTGRES_USER=uxbox"
            - "POSTGRES_PASSWORD=uxbox_postgres_password"
        volumes:
            - uxbox_db:/var/lib/postgresql/data

    backend:
        build: ./backend
        #image: monogramm/uxbox:backend
        #restart: always
        depends_on:
            - db
        ports:
            - "6060:6060"
        environment:
            # HTTP setup
            - "UXBOX_HTTP_SERVER_DEBUG=false"
            # Database setup
            - "UXBOX_DATABASE_USERNAME=uxbox"
            - "UXBOX_DATABASE_PASSWORD=uxbox_postgres_password"
            - "UXBOX_DATABASE_NAME=uxbox"
            - "UXBOX_DATABASE_SERVER=db"
            - "UXBOX_DATABASE_PORT=5432"
            # Mail setup
            - "UXBOX_EMAIL_REPLY_TO=no-reply@uxbox.io"
            - "UXBOX_EMAIL_FROM=no-reply@uxbox.io"
            # STMP setup
            - "UXBOX_SMTP_HOST=localhost"
            - "UXBOX_SMTP_PORT=25"
            - "UXBOX_SMTP_USER=uxbox"
            - "UXBOX_SMTP_PASSWORD=youshouldoverwritethiswithsomethingelse"
            - "UXBOX_SMTP_SSL=false"
            - "UXBOX_SMTP_TLS=false"
            - "UXBOX_SMTP_ENABLED=false"
            # Security setup
            - "UXBOX_SECRET=youshouldoverwritethiswithsomethingelse"

    frontend:
        build: ./frontend
        #image: monogramm/uxbox:frontend
        #restart: always
        depends_on:
            - backend
        ports:
            - 80:80
        environment:
            - "API_URL=http://127.0.0.1:6060/api"
