---
version: "3.5"

networks:
  penpot:

volumes:
  postgres_data:
  user_data:
  backend_data:

services:
  penpot-frontend:
    image: "penpotapp/frontend:develop"
    ports:
      - 8080:80

    volumes:
      - backend_data:/opt/data

    depends_on:
      - penpot-backend
      - penpot-exporter
    networks:
      - penpot

  penpot-backend:
    image: "penpotapp/backend:develop"
    volumes:
      - backend_data:/opt/data

    depends_on:
      - penpot-postgres
      - penpot-redis

    environment:
      # Used for creating tokens, important to be true random value
      - PENPOT_SECRET_KEY=provide-here-a-secret-random-key

      # Mainly used in logging, not important setting.
      - PENPOT_HOST=example.penpot

      # Standard database connection parametes (only postgresql is supported):
      - PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
      - PENPOT_DATABASE_USERNAME=penpot
      - PENPOT_DATABASE_PASSWORD=penpot

      # Redis is used for the websockets notifications.
      - PENPOT_REDIS_URI=redis://penpot-redis/0

      - PENPOT_STORAGE_BACKEND=fs
      - PENPOT_STORAGE_FS_DIRECTORY_=/opt/data/assets
      - PENPOT_LOCAL_ASSETS_URI=http://penpot-frontend/internal/assets

      # Enable telemetry Telemetry consists on sending collected
      # anonymous data to us in order to learn about the use of penpot
      # and improve the platform based on real scenarios. If yo want
      # to help us, please leave it enabled. In any case you can see
      # the source code of the telemetry client and server in the
      # penpot repository, all is open source.
      - PENPOT_TELEMETRY_ENABLED=true
      - PENPOT_TELEMETRY_URI=https://telemetry.penpot.app

      # Email sending configuration.
      - PENPOT_SMTP_ENABLED=false
      - PENPOT_SMTP_DEFAULT_FROM=no-reply@example.com
      - PENPOT_SMTP_DEFAULT_REPLY_TO=no-reply@example.com
      # - PENPOT_SMTP_HOST=...
      # - PENPOT_SMTP_PORT=...
      # - PENPOT_SMTP_USERNAME=...
      # - PENPOT_SMTP_PASSWORD=...
      # - PENPOT_SMTP_TLS=true
      # - PENPOT_SMTP_SSL=false
      # - PENPOT_GOOGLE_CLIENT_ID=...
      # - PENPOT_GOOGLE_CLIENT_SECRET=...

      - PENPOT_ASSERTS_ENABLED=false
      - PENPOT_DEBUG=false

    networks:
      - penpot

  penpot-exporter:
    image: "penpotapp/exporter:develop"
    environment:
      - PENPOT_PUBLIC_URI=http://penpot-frontend
    networks:
      - penpot

  penpot-postgres:
    image: "postgres:13"
    restart: always
    stop_signal: SIGINT

    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - penpot

  penpot-redis:
    image: redis:6
    restart: always
    networks:
      - penpot
