version: "3"

volumes:
  backend_m2:
  backend_data:
  postgres_data:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.177.10.0/24

services:
  postgres:
    image: postgres:12
    restart: always
    stop_signal: SIGINT
    ports:
      - 5432:5432
    environment:
      - POSTGRES_INITDB_ARGS="--data-checksums"
      - POSTGRES_DB=uxbox
      - POSTGRES_USER=uxbox
      - POSTGRES_PASSWORD=uxbox_postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: uxbox-backend:latest
    restart: always
    depends_on:
      - postgres
      - smtp
    ports:
      - 6060
    volumes:
      - backend_data:/srv/uxbox/data
      - backend_m2:/root/.m2

    environment:
      # HTTP setup
      # - CLOJURE_OPTIONS=
      - UXBOX_HTTP_SERVER_CORS="*"

      # Media & Assets
      - UXBOX_MEDIA_URI="/media/"
      - UXBOX_ASSETS_URI="/static/"
      - UXBOX_MEDIA_DIRECTORY="data/media"
      - UXBOX_ASSETS_DIRECTORY="data/static"

      # Database setup (using the `postgres` container)
      - UXBOX_DATABASE_URI="postgresql://postgres/uxbox"
      - UXBOX_DATABASE_USERNAME="uxbox"
      - UXBOX_DATABASE_PASSWORD="uxbox_postgres_password"

      # Mail setup
      - UXBOX_EMAIL_REPLY_TO="no-reply@uxbox.io"
      - UXBOX_EMAIL_FROM="no-reply@uxbox.io"

      # STMP setup (using the `smtp` container)
      - UXBOX_SMTP_HOST="smtp"
      - UXBOX_SMTP_PORT=25
      - UXBOX_SMTP_USER="uxbox"
      # - UXBOX_SMTP_PASSWORD=""
      - UXBOX_SMTP_SSL=false
      - UXBOX_SMTP_TLS=false
      - UXBOX_SMTP_ENABLED=false

  frontend:
    image: uxbox-frontend:latest
    restart: always
    depends_on:
      - backend
    ports:
      - 8080:8080
    volumes:
      - backend_data:/srv/uxbox/

  frontend-dev:
    image: uxbox-frontend-dbg:latest
    restart: always
    depends_on:
      - backend
    ports:
      - 8081:8080
    volumes:
      - backend_data:/srv/uxbox/

  smtp:
    image: mwader/postfix-relay
    restart: always
    environment:
      - POSTFIX_myhostname=smtp.uxbox.io
      - OPENDKIM_DOMAINS=smtp.uxbox.io


